#!/usr/bin/env bash
set -euo pipefail
# Media module contract: compact now-playing pill, expandable later.
app="$HOME/.config/quickshell/StatusbarApp"
fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
need() { grep -q "$2" "$1" || fail "$3"; }

[[ -f "$app/MediaModule.qml" ]] || fail "MediaModule.qml missing"
need "$app/MediaModule.qml" "Quickshell.Services.Mpris" "MediaModule must use Mpris service"
need "$app/MediaModule.qml" "Mpris.players" "MediaModule must read Mpris.players"
need "$app/MediaModule.qml" "collapsed" "MediaModule must hide when nothing plays"
need "$app/MediaModule.qml" "function activate" "MediaModule must expose activate() for click/keyboard"
need "$app/MediaModule.qml" "isPlaying" "MediaModule must toggle play/pause"
need "$app/MediaModule.qml" "previous()" "MediaModule must expose previous() for later expansion"
need "$app/MediaModule.qml" "next()" "MediaModule must expose next() for later expansion"
need "$app/MediaModule.qml" "togglePlaying" "MediaModule must call togglePlaying(), isPlaying is read-only"
grep -q "isPlaying = !" "$app/MediaModule.qml" && fail "MediaModule must not assign read-only isPlaying"
need "$app/StatusbarWindow.qml" "cMedia" "StatusbarWindow must register cMedia"
need "$app/StatusbarWindow.qml" "\"media\"" "StatusbarWindow must map \"media\""
need "$app/config.json" "\"media\"" "config.json defaults must include media"
need "$app/StatusbarWindow.qml" '"left": \["launcher", "logo", "workspaces", "media"\]' "logo must sit next to launcher, media after workspaces"
need "$app/StatusbarWindow.qml" '"center": \["weather", "clock", "swaync"\]' "center must be weather + clock + swaync"
need "$app/config.json" '"left":.*"workspaces", "media"' "config.json media must sit directly after workspaces"
need "$app/MediaPanel.qml" "Mpris.players" "MediaPanel must list all players"
need "$app/MediaPanel.qml" "previous()" "MediaPanel rows must skip backward"
need "$app/MediaPanel.qml" "trackArtUrl" "MediaPanel rows must show cover art"
# The panel must not slide through the pill on open: transit steals hover and
# retriggers dwell/close in a loop. It fades in place instead.
grep -q "hiddenY" "$app/MediaPanel.qml" && fail "MediaPanel must not slide (hover steal loop)"
need "$app/MediaModule.qml" "onWheel" "MediaModule wheel must cycle players"
need "$app/MediaModule.qml" "totalCount" "MediaModule wheel must span players plus app streams"
need "$app/MediaModule.qml" "selectStream" "MediaModule must pin app streams from panel"
need "$app/MediaModule.qml" "trackWidth" "MediaModule pill width must be fixed regardless of title"
need "$app/MediaModule.qml" "marquee" "MediaModule must scroll overlong titles on hover"
need "$app/MediaPanel.qml" "mprisNames" "MediaPanel must hide streams covered by an MPRIS player (no duplicates)"
need "$app/MediaModule.qml" "mprisNames" "MediaModule wheel must skip streams covered by MPRIS"
need "$app/MediaPanel.qml" "playerctld" "MediaPanel must drop the playerctld proxy mirror (no doubled rows)"
need "$app/MediaModule.qml" "playerctld" "MediaModule must drop the playerctld proxy mirror"
need "$app/MediaModule.qml" "pinnedIndex" "MediaModule must remember pinned player"
need "$app/MediaModule.qml" "mediaToggleRequested" "MediaModule must request dropdown"
need "$app/MediaModule.qml" "dwellTimer" "MediaModule must open dropdown after hover dwell"
need "$app/MediaModule.qml" "mediaOpenRequested" "MediaModule dwell must request open-only"
need "$app/MediaModule.qml" "interval: 250" "MediaModule dwell must be 250ms"
need "$app/MediaModule.qml" "closeTimer" "MediaModule must auto-hide dropdown on leave"
need "$app/MediaModule.qml" "mediaCloseRequested" "MediaModule must request close"
need "$app/StatusbarWindow.qml" "mediaOpen" "StatusbarWindow must own panel state"
need "$app/StatusbarWindow.qml" "MediaPanel" "StatusbarWindow must place MediaPanel"
need "$app/MediaPanel.qml" "canGoPrevious" "MediaPanel prev button must respect canGoPrevious (Brave/YouTube single video reports false)"
need "$app/MediaPanel.qml" "canGoNext" "MediaPanel next button must respect canGoNext (Brave/YouTube single video reports false)"
need "$app/MediaPanel.qml" "appStreams" "MediaPanel must list PipeWire app streams fallback"
need "$app/MediaPanel.qml" "application.name" "MediaPanel app rows must show application.name"
grep -q "Slider" "$app/MediaPanel.qml" && fail "MediaPanel must not use sliders (media, not volume)"
need "$app/MediaPanel.qml" "Flickable" "MediaPanel app rows must scroll (Flickable)"
need "$app/MediaPanel.qml" "audio.muted = !modelData.audio.muted" "MediaPanel fallback card must toggle mute as pause"
printf 'PASS: media module wired and expandable\n'
