;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cdv C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cd C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cd C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cd C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cd C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here

e.=explorer .
pwd=cd
clear=cls
vi=vim $*
eoff=@echo echo off  
ps=powershell  
cmderr=cdv "%CMDER_ROOT%"
adda= git add --all  
upa= git push --all  
g= git $*  
a= alias $*  
games= cdv "C:\Users\%USERNAME%\Documents\game fast\" $t explorer .  
link= cdv C:\ProgramData\Microsoft\Windows\Start Menu\Programs  
monk= start https://monkeytype.com/  
in= cat input.txt  
cpremote=start https://github.com/orsnaro/CPP_bgnrCOMP_Study  
com=git commit -m"# $*"  
chk=git checkout $*  
bye=git push $t shutdown /s  
stube=start https://www.youtube.com/results?search_query=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bmpremote= start https://github.com/orsnaro/Static_chroma_bmp  
allgit=git add --all $t git commit -m "# $*" $t git push  
mspremote= start https://github.com/orsnaro/MSP-MachineLearning-tasks  
cporg=cdv C:\Users\%USERNAME%\repo_CPP_COMP_study  
bmporg= cdv C:\Users\%USERNAME%\repo_CHROMA_BMP_proj  
msporg=cdv C:\Users\%USERNAME%\repo_MSP_ML_study  
interporg=cdv C:\Users\%USERNAME%\repo_CRAFTING_INTERPRETERS_study  
tree= tree /f  
hex=xxd -c 16 $*  
chex=xxd -c 16 -i $*  
cpplng=clang++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
hddf= cdv f:  
embedorg=cdv C:\Users\%USERNAME%\repo_embedded-C  
sqlite= sqlite3  
sql= sqlite3  
cm=cmder  
d=exit  
en=echo $*  
tsk=tasklist $1 $b sort  
klterm= taskkill /im WindowsTerminal.exe /f  
jp= start C:\Users\%USERNAME%\win_trm_mnmzd.exe $t jupyter-lab  
cpp=g++ $* -Wall -Wextra -g -o active $t check_file_exist.bat  
allgitdiff= allgitdiff.bat  
allgitall= allgitall.bat  
parkremote=start https://github.com/Gehad-AboElmagd/smart_parking_system  
keyorg= cdv C:\Users\%USERNAME%\repo_KeyRec_tool  
exe-keyrec=pyinstaller --name=KeyRec-Asda --specpath=C:\Users\%USERNAME%\repo_KeyRec_tool\dump --distpath=C:\Users\%USERNAME%\repo_KeyRec_tool\KeyRec-tool\KeyRec-Asda_V2.1.0B\ --onefile --icon=C:\Users\%USERNAME%\repo_KeyRec_tool\dump\KeyRec.ico C:\Users\%USERNAME%\repo_KeyRec_tool\source\keyrec_1window_V2.1.0B.py  
asdarec= KeyRec-Asda  
kltsk=taskkill /im "$*"  /f  
remotes=start https://github.com/  
py=python  $*  
log=git log --all --graph --decorate --oneline  
phporga=cd c:\xampp\htdocs\repo_ps_site\ $t code c:\xampp\htdocs\repo_Ps_site $t C:\xampp\xampp-control.exe $t start http://localhost/repo_ps_site/index.php $t start http://localhost/phpmyadmin  
loga=git log --all --graph --decorate --stat  
logme=git log --all --graph  --decorate --stat --author="Omar Rashad Salem"  
ffindhere=dir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\*$**" /s  
movdis= mmt /MoveWindow 1 Process Discord.exe  
orsorg= cd C:\Users\%USERNAME%\repo_Orsnaro  
phone="C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCoLtd.SamsungFlux_4.9.704.0_x64__wyx1vj98g3asy\SamsungFlow.exe"  
gmail= start https://www.gmail.com  
s=start https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sound=chrome https://soundcloud.com  
parkorg=cdv C:\Users\%USERNAME%\repo_Smart_parking_system\  
oldorg=cdv "C:\Users\%USERNAME%\repo_Old_projects_stash"  
speed=speedtest.exe  
botorg=cdv C:\Users\%USERNAME%\repo_Discord_bot_ai\  
clock=start ms-clock:  
ntype=start https://www.nitrotype.com/  
typer=start https://play.typeracer.com/  
stat=git status  
sbrave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
mx=sndvol.exe  
bothost=bothost.lnk  
cprn=g++ cp.cpp -o CP.exe $t @echo  CP.exe is running .. $t CP.exe  $t del CP.exe  
notpushed= git log --stat --branches --not --remotes  
conforg=cdv "C:\Users\%USERNAME%\repo_My_configs_cmder"  
allcode=code C:\users\%USERNAME%\repo_My_configs_cmder\all_local_repo_vs.code-workspace  
ls=ls --show-control-chars -F -A --color $*  
shorts=start C:\Users\OmarPc\repo_MY_configs_cmder\shortcuts.md  
ec2bot1=ssh -i "c:\Users\OmarPc\aws-ec2-discordpy-bot-wiz.pem" ubuntu@ec2-3-75-231-15.eu-central-1.compute.amazonaws.com  
locom=commited_not_pushed.bat  
strtvm=start /min setup_vbox_ubuntu.bat  
sshvbox=ssh -p 2022 orsnaro@127.0.0.1  
env=cdv C:\Users\OmarPc\py_envs\  
phporg=cdv c:\xampp\htdocs\repo_ps_site\ 1  
root=cdv C:\Users\OmarPc 1  
gtubelst=youtube-dl $*  
tele="C:\Users\OmarPc\AppData\Roaming\Telegram Desktop\Telegram.exe" $t  timeout /t 2 $t mmt  /MoveWindow 1  Process "Telegram.exe" /WindowTop -10 /WindowLeft 0 /WindowWidth 900 /WindowHeight 1600 what=chrome --app=https://web.whatsapp.com/ $t mmt /MoveWindow 1  Title  "web.whatsapp.com" /WindowTop 0 /WindowLeft -10 /WindowWidth 910 /WindowHeight 1600  
spot="C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.210.760.0_x86__zpdnekdrzrea0\Spotify.exe" $t timeout /t 2 $t mmt /MoveWindow 1  Process "Spotify.exe" /WindowTop 0 /WindowLeft -10 /WindowWidth 910 /WindowHeight 1600  
schrome=chrome "https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9" $t  timeout /t 2 $t mmt /MoveWindow 1 Process "chrome.exe" /WindowTop 0 /WindowLeft -10 /WindowWidth 910 /WindowHeight 1600  
bin=cd /d c:\Users\OmarPc\repo_My_configs_cmder\cmder\bin\  
sbravecog="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --incognito https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
bravecog="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --incognito $*  
grp=grep  -i -n -H -G  $* --color  
strtvbox= start /min setup_vbox_ubuntu.bat  
desk=chdir /d c:\Users\OmarPc\Desktop\  
comp=cdv c:\users\OmarPc\repo_CPP_COMP_study $t code . $t start ms-clock: $t chrome  https://www.calculatorsoup.com/calculators/math/modulo-calculator.php $t chrome https://docs.google.com/spreadsheets/d/1Dz4BqGn9Ddc3ptAw4J8kwXHsRU_hLtaBuioPbCCkScw/edit#gid=855203541 $t chrome https://docs.google.com/spreadsheets/d/1DtuVRvM_eikroXM7fFBUA78ldjOEDTRP_lYsnVHtf_M/edit#gid=593476609 $t chrome https://codeforces.com/contests $t chrome https://www.codechef.com/contests $t chrome https://www.hackerrank.com/dashboard $t chrome https://github.com/orsnaro/CP-Beginner-Cheat-Sheets/blob/main/README.md  
diff=git diff $*  
disweb=move_dicord_webapp_brave.bat  
dis=powershell.exe -Command "Start-Process powershell -WindowStyle Hidden -ArgumentList 'Start-Process opendiscord_2nd_monitor.bat -WindowStyle Hidden'" $t mmt /MoveWindow 1 Process "Discord.exe"  
brave="C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" $*  
twt=start https://www.twitch.tv/search?term=$1%20$2%20$3%20$4%20$5%20$6%20$7%20$8%20$9  
find=tasklist  $b sort $b  grep -i -e "image name" -e "=" -e "$*"  --color  
ua=alias /d $*  
unalias=alias /d $*  
cd=cdv $*  
what=chrome --app=https://web.whatsapp.com/ $t timeout /t 2 $t  mmt /MoveWindow 1  Title  "web.whatsapp.com" /WindowTop 0 /WindowLeft -10 /WindowWidth 910 /WindowHeight 1600  
look=start https://outlook.office.com/mail/?actSwt=true  
sgxcog=opera --incognito https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
sgx=opera https://www.google.com/search?q=$1+$2+$3+$4+$5+$6+$7+$8+$9  
gxcog=opera --incognito $*  
gx=opera $*  
ocd=cd $*  
gproj=cd /d "E:\omar-work\Grad Proj Reality SimSuit"  
jptopdf=jupyter-nbconvert --to pdf $*  
twtdisorg= cdv C:\Users\OmarPc\repo_Tweet_discord\  
mongo=mongosh $*  
allgitstat=allgitstat.bat $*  
bard= opera https://bard.google.com/  
csrn=csc cp.cs $t CP.exe  $t del CP.exe  
cs= csc $1 $t main.exe $t  del main.exe  
dtrn=dotnet run  
dtbuild=dotnet build  
doneprob=save_N_push_solved_prob.bat cpp  
pydoneprob=save_N_push_solved_prob_py.bat py  
addtodo=add_todo_prob.bat cpp  
csaddtodo=add_todo_prob.bat cs  
csdoneprob=save_N_push_solved_prob.bat cs  
pyaddtodo=add_todo_prob.bat py  
calc_lines=git ls-files -z  
flip=py C:\Users\OmarPc\repo_My_configs_cmder\cmder\bin\flip_screen.py  
gorg=cdv C:\Users\OmarPc\repo_Reality_SimSuit_grad_project  
ngrp=grep  -v -i -n -H -G  $* --color  
grep=grep -i $* --color  
gptg=chrome --app=https://chat.openai.com  
gpt=python C:\Users\OmarPc\others_repo_GptCli\src\chatgpt.py $*  
~1=~0,-1  
