-- Generated by nwg-displays on 2026-09-26 at 18:24:03. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@180.0",
    position = "2404x381",
    scale = 1.0,
    bitdepth = 10,
    vrr = 1
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1366x768@59.79",
    position = "1038x768",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "1440x900@59.9",
    position = "4964x768",
    scale = 1,
    vrr = 0
})
